- hosts:          sdlc
  become:         true
  become_user:    '{{ user }}'

  vars:
    tpcds_orc_db: 'tpcds_bin_partitioned_orc_{{ tpcds_size }}'
    results_file: '{{ ansible_date_time.date}}_{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}'

  tasks:
    - name:       Run the analyze sql to build stats for TPCDS Datasets.
      shell:      cd /home/{{ user }}/hive-testbench; beeline -u "jdbc:hive2://{{ zookeeper_server}}:2181/{{ tpcds_orc_db }};serviceDiscoveryMode=zooKeeper;zooKeeperNamespace={{ hs2_zk_namespace }}" -n "{{ tpcds_user }}" -p "{{ user_password }}" -f "./ddl-tpcds/bin_partitioned/analyze.sql"
      tags:
        - stats

    - include_tasks: tpcds_queries.yaml
      loop:
        - 1
        - 2
        - 3
        - 4
      loop_control:
        loop_var: iteration
